chromedp:
  headless: true
  headers:
    user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/100.0.4896.60 Safari/537.36
appmsg:
  query: 每日安全动态推送
  fakeid: MzA5NDYyNDI0MA==
  timeline: 2022-04-05T20:37:42
  dumpformat: html
